/**
 * 페이지의 경로를 관리합니다.
 */
export const enum Paths {
	HOME = 'HOME', // 메인 페이지
	MAIN_TAB = 'MAIN_TAB',
	SETTING = 'SETTING', // 설정 페이지
	TODAY_QUIZ = 'TODAY_QUIZ', //오늘의 퀴즈
	PROVERB_LIST = 'PROVERB_LIST', // 리스트 페이지
	PROVERB_STUDY = 'PROVERB_STUDY', // 학습 모드
	QUIZ = 'QUIZ',
	QUIZ_MODE = 'QUIZ_MODE', // 오답노트
	INIT_TIME_CHANLLENGE = 'INIT_TIME_CHANLLENGE', // 타임 챌린지 진입
	TIME_CHANLLENGE = 'TIME_CHANLLENGE', // 타임 챌린지
	PROVERB_QUIZ_MODE_SELECT = 'PROVERB_QUIZ_MODE_SELECT', // 리스트 퀴즈
	QUIZ_WRONG_REVIEW = 'QUIZ_WRONG_REVIEW',
	TOWER_CHANLLENGE = 'TOWER_CHANLLENGE',
	TOWER_QUIZ = 'TOWER_QUIZ',
	EXAMPLE = 'EXAMPLE',
	MAIN_REFRENCE = 'MAIN_REFRENCE',
	MY_SCORE = 'MY_SCORE',
	FAVORITE = 'FAVORITE', // 즐겨찾기
	MY_PROVERB_BOOK = 'MY_PROVERB_BOOK', // 나만의 속담집
	MY_PROVERB_BOOK_DETAIL = 'MY_PROVERB_BOOK_DETAIL', // 나만의 속담집 상세
	FN_NOTIFICATION = 'FN_NOTIFICATION',
	FN_ADVERTISEMENT = 'FN_ADVERTISEMENT',
	FN_PERMISSION = 'FN_PERMISSION',
	FN_LANGUAGE = 'FN_LANGUAGE',
}
