import { MainDataType } from '@/types/MainDataType';

export const CONST_BADGES: MainDataType.UserBadge[] = [
	// 학습뱃지
	{
		id: 'study_1',
		name: '시작이 반이다',
		description: '첫 번째 국가를 학습했어요!',
		iconType: 'materialIcons',
		icon: 'school',
	},
	{
		id: 'study_10',
		name: '10개국 탐험가',
		description: '총 10개 국가 이상 학습했어요!',
		iconType: 'materialIcons',
		icon: 'travel-explore',
	},
	{
		id: 'study_50',
		name: '지식 수집가',
		description: '총 50개 국가 이상 학습했어요!',
		iconType: 'materialIcons',
		icon: 'menu-book',
	},
	{
		id: 'study_100',
		name: '글로벌 학자',
		description: '총 100개 국가 이상 학습했어요!',
		iconType: 'materialIcons',
		icon: 'public',
	},

	/* 퀴즈 뱃지 */
	{
		id: 'europe_master',
		name: '유럽 마스터',
		description: '유럽 국가 문제를 모두 풀었어요!',
		iconType: 'fontAwesome6',
		icon: 'landmark-dome',
	},
	{
		id: 'asia_master',
		name: '아시아 마스터',
		description: '아시아 국가 문제를 모두 풀었어요!',
		iconType: 'materialIcons',
		icon: 'account-balance',
	},
	{
		id: 'americas_master',
		name: '아메리카 마스터',
		description: '아메리카 국가 문제를 모두 풀었어요!',
		iconType: 'materialIcons',
		icon: 'public',
	},
	{
		id: 'africa_master',
		name: '아프리카 마스터',
		description: '아프리카 국가 문제를 모두 풀었어요!',
		iconType: 'materialCommunityIcons',
		icon: 'elephant',
	},
	{
		id: 'oceania_master',
		name: '오세아니아 마스터',
		description: '오세아니아 국가 문제를 모두 풀었어요!',
		iconType: 'materialIcons',
		icon: 'waves',
	},
	{
		id: 'antarctica_master',
		name: '남극 마스터',
		description: '남극 국가 문제를 모두 풀었어요!',
		iconType: 'materialIcons',
		icon: 'ac-unit',
	},
	{
		id: 'level1_master',
		name: '레벨 1 마스터',
		description: '레벨 1 국가 문제를 모두 풀었어요!',
		iconType: 'fontAwesome6',
		icon: 'seedling',
	},
	{
		id: 'level2_master',
		name: '레벨 2 마스터',
		description: '레벨 2 국가 문제를 모두 풀었어요!',
		iconType: 'fontAwesome6',
		icon: 'leaf',
	},
	{
		id: 'level3_master',
		name: '레벨 3 마스터',
		description: '레벨 3 국가 문제를 모두 풀었어요!',
		iconType: 'fontAwesome6',
		icon: 'tree',
	},
	{
		id: 'level4_master',
		name: '레벨 4 마스터',
		description: '레벨 4 국가 문제를 모두 풀었어요!',
		iconType: 'fontAwesome6',
		icon: 'trophy',
	},
	{
		id: 'world_master',
		name: '세계수도 마스터',
		description: '전 세계 국가 문제를 모두 풀었어요!',
		iconType: 'materialCommunityIcons',
		icon: 'earth',
	},
	{
		id: 'quiz_1',
		name: '첫 퀴즈 도전자',
		description: '첫 문제에 도전했어요! 멋진 출발이에요!',
		iconType: 'materialIcons',
		icon: 'looks-one',
	},
	{
		id: 'quiz_10',
		name: '10문제 도전 뱃지',
		description: '10문제를 풀었어요! 계속해서 실력을 쌓아가고 있어요!',
		iconType: 'materialIcons',
		icon: 'military-tech',
	},
	{
		id: 'quiz_50',
		name: '50문제 도전 뱃지',
		description: '50문제를 풀다니! 이 정도면 퀴즈 고수!',
		iconType: 'materialIcons',
		icon: 'workspace-premium',
	},
	{
		id: 'quiz_100',
		name: '100문제 도전 뱃지',
		description: '놀라워요! 100문제나 풀며 진정한 정복자에 가까워지고 있어요!',
		iconType: 'materialIcons',
		icon: 'emoji-events',
	},
	{
		id: 'quiz_200',
		name: '200문제 도전 뱃지',
		description: '200문제 돌파! 당신은 이제 퀴즈 월드 클래스!',
		iconType: 'materialIcons',
		icon: 'grade',
	},
	{
		id: 'combo_3',
		name: '콤보 달성 3',
		description: '콤보 3 연속! 시작이 좋네요!',
		iconType: 'materialCommunityIcons',
		icon: 'fire',
	},
	{
		id: 'combo_5',
		name: '콤보 달성 5',
		description: '콤보 5! 집중력이 빛났어요!',
		iconType: 'materialCommunityIcons',
		icon: 'fire',
	},
	{
		id: 'combo_10',
		name: '콤보 달성 10',
		description: '콤보 10은 아무나 못해요! 정말 대단해요!',
		iconType: 'materialCommunityIcons',
		icon: 'fire',
	},
	{
		id: 'combo_15',
		name: '콤보 달성 15',
		description: '콤보 15! 퀴즈 신이 당신에게 미소 짓고 있어요!',
		iconType: 'materialCommunityIcons',
		icon: 'fire',
	},
	{
		id: 'combo_20',
		name: '콤보 달성 20',
		description: '콤보 20?! 완전 전설이에요! 당신은 진정한 마스터!',
		iconType: 'materialCommunityIcons',
		icon: 'fire-alert',
	},
	{
		id: 'score_traveler',
		name: '여행 초보자',
		description: '600점 달성! 퀴즈 여행을 시작했어요!',
		iconType: 'fontAwesome6',
		icon: 'seedling',
	},
	{
		id: 'score_conqueror',
		name: '대륙 정복자',
		description: '1200점! 대륙을 정복하는 당신의 열정에 박수를!',
		iconType: 'fontAwesome6',
		icon: 'leaf',
	},
	{
		id: 'score_explorer',
		name: '국가 탐험가',
		description: '1800점 달성! 이제 세계가 당신의 무대예요!',
		iconType: 'fontAwesome6',
		icon: 'tree',
	},
	{
		id: 'score_master',
		name: '월드 마스터',
		description: '2460점 달성! 이건… 그냥 월드 클래스입니다!',
		iconType: 'fontAwesome6',
		icon: 'trophy',
	},
];
