export enum MainStorageKeyType {
	TODAY_QUIZ_LIST = 'TodayQuizList',
	USER_STUDY_HISTORY = 'UserStudyHistory', // 학습
	TIME_CHALLENGE_HISTORY = 'TimeChallengeHistory', // 챌린지
	USER_QUIZ_HISTORY = 'UserQuizHistory', // 퀴즈
	SETTING_INFO = 'SettingInfo',
	TOWER_CHALLENGE_PROGRESS = 'TOWER_CHALLENGE_PROGRESS',
	FAVORITES_STORAGE_KEY = 'FAVORITES_STORAGE_KEY',
	USER_PROVERB_BOOKS = 'USER_PROVERB_BOOKS', // 나만의 속담집 목록
	USER_PROVERB_PRACTICE_RECORDS = 'USER_PROVERB_PRACTICE_RECORDS', // 속담집 연습 기록
}
