######## 최상단
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '16.0'
prepare_react_native_project!

######## Firebase 설정
$RNFirebaseAnalyticsWithoutAdIdSupport = false
$RNFirebaseAnalyticsEnableAdSupport = true
$RNFirebaseAsStaticFramework = true


######## 권한 설정
setup_permissions([
  'Notifications',
  'Camera',
])

######## 메인 타겟
target 'ProverbQuiz' do
  config = use_native_modules!
  
  # [firebase] Google Firebase option
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      end
    end

    # 비트코드 제거
    bitcode_strip_path = `xcrun --find bitcode_strip`.strip
    def strip_bitcode_from_framework(bitcode_strip_path, framework_path)
      binary_name = File.basename(framework_path)
      binary_path = File.join(framework_path, binary_name)
      if File.exist?(binary_path)
        puts "🔧 Stripping bitcode: #{binary_path}"
        system("#{bitcode_strip_path} #{binary_path} -r -o #{binary_path}")
      end
    end

    Dir.glob("ios/Pods/**/*.framework").each do |framework_dir|
      strip_bitcode_from_framework(bitcode_strip_path, framework_dir)
    end
  end
end